config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :policies
  resources :companies
  resources :employees

  get 'settings/new-bulk-import', to: 'settings#new_bulk_import'
  post 'settings/create-bulk-import', to: 'settings#create_bulk_import'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company
  has_and_belongs_to_many :policies

  validates_presence_of :name, :email
  validates :email, uniqueness: true

  acts_as_nested_set
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :email, :phone, :company_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div  class="card-body">
  <%= form_with(model: employee, local: true) do |form| %>
    <%= form_group_for form, :name  do %>
      <%= form.text_field :name, autofocus: true, class: "form-control" %>
    <% end %>

    <%= form_group_for form, :email  do %>
      <%= form.email_field :email, class: "form-control" %>
    <% end %>

    <%= form_group_for form, :phone  do %>
      <%= form.text_field :phone, class: "form-control" %>
    <% end %>

    <%= form_group_for form, :company_id  do %>
      <%= form.collection_select :company_id, Company.all, :id, :name, {prompt: "Select Company"}, { class: 'form-control' } %>
    <% end %>

    <div class="actions mt-2">
      <%= form.submit class:'btn btn-primary' %>
      <%= link_to "Back", companies_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/employees/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="card mt-5">
        <div class="card-header">
          <h2>Edit Employee</h2>
        </div>
        <%= render 'form', employee: @employee %>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-6">
          <h1>Employees</h1>
        </div>
        <div class="col-md-6 text-right">
          <%= link_to 'New Employee', new_employee_path, class: 'btn btn-primary' %>
        </div>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Manager</th>
            <th>Company</th>
            <th colspan="3" width="20%">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.name %></td>
              <td><%= employee.email %></td>
              <td><%= employee.phone %></td>
              <td><%= employee.parent.email if employee.parent %></td>
              <td><%= employee.company.name %></td>
              <td><%= link_to 'Show', employee %></td>
              <td><%= link_to 'Edit', edit_employee_path(employee), id: "edit_#{employee.id}" %></td>
              <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="card mt-5">
        <div class="card-header">
          <h2>New Employee</h2>
        </div>
        <%= render 'form', employee: @employee %>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Company:</strong>
  <%= @employee.company.name %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>