config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :policies
  resources :companies
  resources :employees

  get 'settings/new-bulk-import', to: 'settings#new_bulk_import'
  post 'settings/create-bulk-import', to: 'settings#create_bulk_import'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<div id="flash" class='text-center'>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %>" style="margin-bottom:0">
      <% unless value == true  %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value.html_safe %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: 'nav-link active' %>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to "Import Data", settings_new_bulk_import_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "Companies", companies_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "Employees", employees_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "Policies", policies_path, class: 'nav-link' %>
    </li>
  </ul>
</nav>