config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :policies
  resources :companies
  resources :employees

  get 'settings/new-bulk-import', to: 'settings#new_bulk_import'
  post 'settings/create-bulk-import', to: 'settings#create_bulk_import'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees
  has_many :policies

  validates :name, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div  class="card-body">
  <%= form_with(model: company, local: true) do |f| %>

    <%= form_group_for f, :name  do %>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    <% end %>

    <div class="actions mt-2">
      <%= f.submit class:'btn btn-primary' %>
      <%= link_to "Back", companies_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/companies/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 mx-auto">
      <div class="card mt-5">
        <div class="card-header">
          <h2>Edit Company</h2>
        </div>
        <%= render 'form', company: @company %>
      </div>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <h1>Companies</h1>
      </div>
      <div class="col-md-6 text-right">
        <%= link_to 'New Company', new_company_path, class: 'btn btn-primary' %>
      </div>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3" width="30%">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.name %></td>
            <td><%= link_to 'Show', company %></td>
            <td><%= link_to 'Edit', edit_company_path(company), id: "edit_#{company.id}" %></td>
            <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/companies/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 mx-auto">
      <div class="card mt-5">
        <div class="card-header">
          <h2>New Company</h2>
        </div>
        <%= render 'form', company: @company %>
      </div>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>