config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :policies
  resources :companies
  resources :employees

  get 'settings/new-bulk-import', to: 'settings#new_bulk_import'
  post 'settings/create-bulk-import', to: 'settings#create_bulk_import'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/policy.rb
class Policy < ApplicationRecord
  belongs_to :company
  has_and_belongs_to_many :employees

  validates :name, uniqueness: true, presence: true
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]

  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
  end

  # GET /policies/new
  def new
    @policy = Policy.new
  end

  # GET /policies/1/edit
  def edit
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(policy_params)

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    respond_to do |format|
      if @policy.update(policy_params)
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { render :show, status: :ok, location: @policy }
      else
        format.html { render :edit }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url, notice: 'Policy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:name, :company_id)
    end
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/policies/_form.html.erb
<div  class="card-body">
  <%= form_with(model: policy, local: true) do |form| %>
    <%= form_group_for form, :name  do %>
      <%= form.text_field :name, autofocus: true, class: "form-control" %>
    <% end %>

    <%= form_group_for form, :company_id  do %>
      <%= form.collection_select :company_id, Company.all, :id, :name, {prompt: "Select Company"}, { class: 'form-control' } %>
    <% end %>

    <div class="actions mt-2">
      <%= form.submit class:'btn btn-primary' %>
      <%= link_to "Back", policies_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/policies/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 mx-auto">
      <div class="card mt-5">
        <div class="card-header">
          <h2>Edit Policy</h2>
        </div>
        <%= render 'form', policy: @policy %>
      </div>
    </div>
  </div>
</div>

app/views/policies/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <h1>Policies</h1>
      </div>
      <div class="col-md-6 text-right">
        <%= link_to 'New Policy', new_policy_path, class: 'btn btn-primary' %>
      </div>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Company</th>
          <th colspan="3" width="30%">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @policies.each do |policy| %>
          <tr>
            <td><%= policy.name %></td>
            <td><%= policy.company.name %></td>
            <td><%= link_to 'Show', policy %></td>
            <td><%= link_to 'Edit', edit_policy_path(policy), id: "edit_#{policy.id}" %></td>
            <td><%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/policies/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 mx-auto">
      <div class="card mt-5">
        <div class="card-header">
          <h2>New Policy</h2>
        </div>
        <%= render 'form', policy: @policy %>
      </div>
    </div>
  </div>
</div>

app/views/policies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @policy.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @policy.company.name %>
</p>

<%= link_to 'Edit', edit_policy_path(@policy) %> |
<%= link_to 'Back', policies_path %>